### ISSUE TITLE
Import of Package List in package ViewList

### ISSUE THREAD

**Issue by taquiles** [sscaff1/feathers-webpack-react-todos#1]
Hi Steven,

I believe you mispelled "Lists" Package when importing it in ListView:

    "import { Lists } from './lists';"

After changing it, capitalizing the first letter, I managed to see your simple but instructive example working.
Still learning how to fly with "feathers.js" ... :-)

**Comment by sscaff1** [comment]
Thanks for the feedback. I haven't look at this repo in some time. Please feel free to submit a PR and I will accept.

**Comment by taquiles** [comment]
Hi Steven, 
PR created.

**Comment by sscaff1** [comment]
Accepted #2
